function generateJobTitle() {
	// Executive Pun Supervisor
	
	var levels = [
		'Lead',
		'Lead',
		'Chief',
		'Executive',
		'Corporate',
		'Main',
		'Junior',
		'Senior',
		'Principal',
		'Technical',
		'Mechanical',
		'Full Stack',
		'Deputy',
		'First',
		'Second',
		'Vice',
		'Professional',
		'Backup',
		'Cute',
		'Pirate',
		'Unofficial',
		'Wannabe',
		'Experienced',
		'Highly Productive',
		'Cheeky',
		'Creative',
		'Superior',
		'',
	]
	var subjects = [
		'Creeper',
		'Feature',
		'Skin',
		'Skyblock',
		'Dinosaur',
		'Furniture',
		'Block',
		'Production',
		'Sound',
		'Design',
		'People',
		'Level',
		'Keyart',
		'Anime',
		'Tech',
		'HR',
		'Recruitment',
		'Marketing',
		'Explosives',
		'Model',
		'Molang',
		'Hiring',
		'Hiring and Firing',
		'Bee',
		'Bug',
		'QA',
		'Rubber Duck',
		'Algorithm',
		'Something',
		'Googling',
		'Trial and Error',
		'Button Finding',
		'Recursion',
		'Diversity',
		'Furniture Delivery',
		'Pun',
		'Joke',
		'Slogan',
		'Cheesy Dialog',
		'Crash',
		'Payout',
		'Feature Creep',
		'Quality',
		'Level Design',
		'Lucky Block',
		'Skinpack',
		'Food Skinpack',
		'Drama',
		'Destruction',
		'Texture Pack',
		'Exposure',
		'Cave Update',
		'High School Anime',
		'PARTY',
		'Procrastination',
		'Boat Fixing',
		'Motivation',
		'Money',
		'Cash',
		'Communication',
		'Timezone',
		'Extreme Pirate Beauty',
		'Cute Vegetable High School Kingdom',
		'Vibrant Visuals',
		'Yolo Life',
		'Quality Restriction',
		'Mass Production',
		'Planned Obsolescence',
		'Player Frustration',
		'Anticlimactic',
		'Supervising',
		'Directing',
		'Artistry',
		'Production',
		'Engineering',
		'Rebranding',
		'Corporate',
		'Copy Paste',
		'Copying from PlanetMinecraft',
		'Backup',
		'Voxel',
		'Sneaker Collection',
		'Meme',
		'LagFox',
		'"Other"',
	]
	var jobs = [
		'Supervisor',
		'Artist',
		'Officer',
		'Creator',
		'Division Supervisor',
		'Implementation Manager',
		'Guru',
		'Expert',
		'Supply Manager',
		'Coordinator',
		'Consultant',
		'Producer',
		'Director',
		'Developer',
		'Builder',
		'Lead',
		'Leader',
		'Designer',
		'Manager',
		'Architect',
		'Assistant',
		'Engineer',
		'CEO',
		'CTO',
		'COO',
		'Guy',
		'Lord',
		'Mechanic',
		'Head of %',
		'Head of % Division',
		'Head of % and %',
		'% and % Expert',
		'Expert for %',
		'Legend',
	]

	let job = jobs.random()
	if (job.includes('%')) {
		return job.replace(/%/g, _ => subjects.random())
	} else {
		return [levels.random(), subjects.random(), job].join(' ')
	}
}